### ISSUE TITLE
Event Page Description

### ISSUE THREAD

**Issue by charger73004** [sohan-4/RPI-MANE-SAC-Website#6]
We needed clarity for the events of page. The events page should have events that contain the following:
1. Image of the event/poster/related image
2. Title of the event (limited to 30 characters)
3. Descirpiton of event
4. date and time of event
5. Link to event/website/discord/related links
This page should be easily edited and managed by the council so that new events could be added and old events could be removed.

**Comment by sohan-4** [comment]
event page implemented
