### ISSUE TITLE
Mandatory vs Non-Mandatory Event inputs

### ISSUE THREAD

**Issue by charger73004** [sohan-4/RPI-MANE-SAC-Website#8]
The only two options that need to be input into the events page when adding a new event should be the title and description. All other options (location, time, date, image, and link) do not need to be mandatory. This allows for virtual meetings to include just a link and for the description to allow for all information to be input to reduce repeat information. Some may not have a link or an image associated with the event.

**Comment by sohan-4** [comment]
events implemented correctly
